### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [xively/concaria#1]
About your code here:

```js
Database.prototype.end = function() {
  // something's wrong with the pg-promise library, this function is documented, don't work tho
  // return this._client.end();
};
```
Nothing is wrong with `pg-promise` :) You are trying to shut down the library on a database level, as opposed to the library level, that's what wrong there.

Change it to:

```js
Database.prototype.end = function() {
  // shutting down the library, not just one database connection:
   pgp.end(); // nothing to return here;
};
```

P.S. Time to up the pg-promise version, perhaps, it's too old by now ;)

But since you are running this thing on Heroku, and it is an HTTP service, you do not need to shut down the library ever!

**Comment by deathbearbrown** [comment]
Thank you @vitaly-t !  The problem we had was when running the code locally, so this is great. We really appreciate the feedback.

**Comment by vitaly-t** [comment]
You are welcome!

**Comment by vitaly-t** [comment]
As for your implementation for `Database.prototype._insertQuery `, you can find a better example of concatenating inserts [here](https://github.com/vitaly-t/pg-promise/wiki/Performance-Boost).

**Comment by ksiegel** [comment]
@vitaly-t Awesome! Thanks for the link, I'll see if we can roll that into an update soon. Glad you're keeping an eye on your npm package
